config/routes.rb
Company::Application.routes.draw do
  get "about", to: "pages#about"
  get "team", to: "pages#team"
  get "investors", to: "pages#investors"
  get "vision", to: "pages#vision"

  get "jobs", to: "jobs#index"
  get "jobs/principles", to: "jobs#principles", as: "job_principles"
  get "jobs/community_manager", to: "jobs#community_manager", as: "community_manager_job"
  get "jobs/content_manager", to: "jobs#content_manager", as: "content_manager_job"
  get "jobs/javascript_developer", to: "jobs#javascript_developer", as: "javascript_developer_job"
  get "jobs/marketer", to: "jobs#marketer", as: "marketer_job"
  get "jobs/mobile_developer", to: "jobs#mobile_developer", as: "mobile_developer_job"
  get "jobs/ruby_on_rails_developer", to: "jobs#ruby_on_rails_developer", as: "ruby_on_rails_developer_job"
  get "jobs/software_developer", to: "jobs#software_developer", as: "software_developer_job"
  get "jobs/web_designer", to: "jobs#web_designer", as: "web_designer_job"

  resources :blog_posts, only: [:index, :show], path: "blog"
  {
    rob_styles: 'rob-styles-joins-meducation',
    taiyab_raja: 'taiyab-raja-joins-meducation',
    new_website: 'new-company-website'
  }.each do |old_path, slug|
    get "blog/#{old_path}", to: redirect("blog/#{slug}")
  end

  get "jobs/ror_developer", to: redirect("jobs/ruby_on_rails_developer")

  root "pages#index"
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :set_jobs
  before_action :set_blog_post_summaries

  private
    def set_page_title(data)
      @page_title = data
    end
 
    def set_jobs
      @jobs = {
        #"Community Manager" => community_manager_job_path,
        "Content Manager" => content_manager_job_path,
        #"Marketer" => marketer_job_path,
        #"Mobile Developer" => mobile_developer_job_path,
        #"JavaScript Developer" => javascript_developer_job_path,
        "Ruby on Rails Developer" => ruby_on_rails_developer_job_path,
        "Software Developer" => software_developer_job_path,
        #"Web Designer" => web_designer_job_path,
      }
    end

    def set_blog_post_summaries
      @blog_post_summaries = BlogPost.select([:id, :slug, :thumb_image, :summary]).order('created_at DESC')
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    set_page_title "Meducation Blog"
    @blog_posts = BlogPost.order("created_at DESC")
  end

  def show
    @blog_post = BlogPost.friendly.find(params[:id])
    set_page_title "Meducation Blog - #{@blog_post.title}"
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    set_page_title "Jobs at Meducation"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    set_page_title "About Meducation"
  end

  def vision
    set_page_title "Meducation's Vision"
  end

  def investors
    set_page_title "Invest in Meducation"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_item_class(section)
    MenuItemClassDeterminer.new(self, section).determine
  end

  def page_title
    @page_title || "Meducation"
  end

  class MenuItemClassDeterminer

    attr_reader :context, :target
    def initialize(context, target)
      @context = context
      @target = target
    end

    def determine
      target == actual ? 'active' : nil
    end

    private

      def actual
        case context.controller_name
        when "pages"
          case context.action_name
          when "index"; :home
          when "about"; :about
          when "vision"; :vision
          when "investors"; :investors
          end
        when "blog"
          :blog
        when "jobs"
          :jobs
        end
      end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def jobs_startup_blurb
    p2 = "We have various "
    p2 << link_to("work principles", job_principles_path)
    p2 << " that apply to everyone in our team."

    content_tag(:p, "Working for a startup like Meducation is a bit different to working for a normal company. You will be part of a close team sharing a journey together where we all get stuck in to help each other, so flexibility and a desire to learn is important to the role. You will have lots of areas of responsibility but lots of people around to support and help you.") + 
    content_tag(:p, p2.html_safe)
  end

  def jobs_apply_blurb
    content_tag(:p, "We are based in Birmingham, UK and are looking for someone who is able to be in the office for at least 2 days per week.") +
    content_tag(:h3, "Up for the challenge?") + 
    content_tag(:p, "If you're interested in working with Meducation let's have a coffee and a chat!") + 
    content_tag(:p) do
      link_to "Email Jeremy »", "mailto:jeremy@meducation.net", class: 'btn-u btn-u-large'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blog/new_website.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Latest Posts
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Blog", blog_path
                %span.divider /
            %li.active New Company Website

=render layout: "blog/layout" do
    =render layout: "blog/new_website_layout" do

        #disqus_thread.margin-top-20
        :javascript
            var disqus_shortname = 'meducation-company';
            var disqus_identifier = 'blog/new_website';
            var disqus_title = 'New Company Website ';
            var disqus_url = 'http://company.meducation.net/blog/new_website';

            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();

app/views/blog_posts/_layout.html.haml
.container
    .row-fluid.blog-page
        .span9= yield
        .span3 
            = render "layouts/blog_posts"

            .headline
                %h3 Latest Tweets
            %a.twitter-timeline{href: "https://twitter.com/Meducation", data: {"widget-id" => "364905287938895872"}}
            %script{src:"//platform.twitter.com/widgets.js"}

app/views/blog_posts/_post_layout.html.haml
.blog.margin-bottom-30
    %h3 
        =link_to blog_post.title, blog_post
    %ul.unstyled.inline.blog-info
        %li
            %i.icon-calendar 
            =blog_post.created_at.to_date.to_s(:long)
        %li
            %i.icon-pencil 
            =blog_post.author
        %li
            %i.icon-tags
            %a{href:"#"} Team
    .blog-img
        =image_tag blog_post.header_image

    =raw blog_post.start_content

    =yield

app/views/blog_posts/show.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Latest Posts
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Blog", blog_posts_path
                %span.divider /
            %li.active= @blog_post.title


=render layout: "blog_posts/layout" do
    =render layout: "blog_posts/post_layout", locals: {blog_post: @blog_post} do
        =raw @blog_post.end_content

        #disqus_thread.margin-top-20
        :javascript
            var disqus_shortname = 'meducation-company';
            var disqus_identifier = '#{blog_post_path(@blog_post)}';
            var disqus_title = '#{@blog_post.title}';
            var disqus_url = 'http://company.meducation.net#{blog_post_path(@blog_post)}';

            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();

app/views/jobs/community_manager.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Job Opportunities
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Jobs", jobs_path
                %span.divider /
            %li.active Community Manager

.container
    .row-fluid
        .span9
            .headline
                %h3 We are Hiring a Community Manager
            .alert.alert-error
                %strong Sorry! 
                This job role has now been 
                =succeed(".") do
                    =link_to "filled by Taiyab Raja", taiyab_raja_blog_post_path
            %p We are building the biggest online community of medics worldwide. We aim to have to two million people register with us over the next five years, ranging from students to senior doctors. Understanding and listening to our community, and reacting to its input is very important to us. To help with this we are looking for an enthusiastic community manager to join our team. 
            %p This job has four main roles:
            %ul
                %li Be the voice of Meducation online, managing our social media, writing blog posts, and being the link between our members and our team
                %li Help guide and facilitate our student and doctor representatives as they spread the word in their communities about Meducation
                %li Understand what our community want Meducation to do for them and feed this back to the rest of the team
                %li Use your knowledge of our community to advise marketers as they put advertising campaigns together

            =jobs_startup_blurb

            %h3 What specific skills are we looking for?
            %p If you're right for this role, you will: 
            %ul
                %li Love working with people, and care about communities
                %li Have the ability to use social media to engage with online communities 
                %li Have excellent copywriting skills and enjoy blogging.
                %li Be able to balance a variety of different projects and tasks
                %li Be highly motivated and be able to take control of your own time and responsibilities
                %li Want to work with a startup and want to learn new skills

            %p It will also help if you have:
            %ul
                %li Worked as a community manager before
                %li Some experience in marketing or growth hacking
                %li Worked in an agile team

            =jobs_apply_blurb
        .span3 
            =render "jobs/sidebar"

app/views/jobs/content_manager.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Job Opportunities
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Jobs", jobs_path
                %span.divider /
            %li.active Content Manager

.container
    .row-fluid
        .span9
            .headline
                %h3 We are Hiring a Content Manager

            %p We are revolutionising the way people use educational material to learn. By working with publishers, our own authors, and our community we are bringing hundreds of thousands of resources together into our innovative educational learning platform. To help us achieve this we are hiring a content manager.
            %p This job has five main roles:
            %ul
                %li Work with our medical co-ordinator and authors to manage the creation of new content
                %li Find people who create resources and encourage them to use Meducation to promote them
                %li Organise and manage the content that is contributed on to Meducation
                %li Work with our marketer and community manager to highlight Meducation's best content
                %li Understand the needs of people creating resources and feed this back to our development team

            =jobs_startup_blurb

            %h3 What specific skills are we looking for?
            %p If you're right for this role, you will: 
            %ul
                %li Be interested or experienced in the creation of educational resources
                %li Be able to balance a variety of different projects and tasks
                %li Be highly motivated and be able to take control of your own time and responsibilities
                %li Want to work with a startup and want to learn new skills

            %p It will also help if you have:
            %ul
                %li Some medical knowledge or experience
                %li Worked in an agile team

            =jobs_apply_blurb

        .span3 
            =render "jobs/sidebar"

app/views/jobs/javascript_developer.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Job Opportunities
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Jobs", jobs_path
                %span.divider /
            %li.active JavaScript Developer

.container
    .row-fluid
        .span9
            .headline
                %h3 We are Hiring a JavaScript Developer
            .alert.alert-error
                %strong Sorry! 
                This job role has now been 
                =succeed(".") do
                    =link_to "filled by Taiyab Raja", taiyab_raja_blog_post_path
            %p We are building an innovative social education platform that will be used by millions of medics. Meducation's frontend is currently being converted into AngularJS SPA applications. We are looking for an experienced JavaScript developer to help with this transition and continue to build the application as it develops. You will need to have excellent JavaScript programming skills and be experienced and comfortable with writing comprehensive test coverage. 
            =jobs_startup_blurb

            %h3 What specific skills are we looking for?
            %p If you're right for this role, you will: 
            %ul
                %li Have 3+ years of JavaScript development experience (either professionally or in demonstrable personal projects)
                %li Have experience of JavaScript testing.
                %li Enjoy working (or at least dabbling) with server side technologies
                %li Be able to balance a variety of different projects and tasks
                %li Be highly motivated and be able to take control of your own time and responsibilities
                %li Want to work with a startup and want to learn new skills

            %p It will also help if you have:
            %ul
                %li A computer science (or related) degree
                %li Experience with AngularJS
                %li Experience with CoffeeScript
                %li Experience with Ruby on Rails
                %li A passion for open source
                %li Worked in an agile team

            =jobs_apply_blurb
        .span3 
            =render "jobs/sidebar"

app/views/jobs/marketer.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Job Opportunities
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Jobs", jobs_path
                %span.divider /
            %li.active Marketer

.container
    .row-fluid
        .span9
            .headline
                %h3 We are Hiring a Marketer
            %p We are building the biggest online community of medics worldwide. We aim to have to two million people register with us over the next five years, ranging from students to senior doctors. Understanding and listening to our community, and reacting to its input is very important to us. To help with this we are looking for an enthusiastic community manager to join our team. 
            %p This job has four main roles:
            %ul
                %li Be the voice of Meduation online, managing our social media, writing blog posts, and being the link between our members and our team
                %li Help guide and facilitate our student and doctor representatives as they spread the word in their communities about Meducation
                %li Understand what our community want Meducation to do for them and feed this back to the rest of the team
                %li Use your knowledge of our community to advise marketers as they put advertising campaigns together

            =jobs_startup_blurb

            %h3 What specific skills are we looking for?
            %p If you're right for this role, you will: 
            %ul
                %li Love working with people, and care about communities
                %li Have the ability to use social media to engage with online communities 
                %li Have excellent copywriting skills and enjoy blogging.
                %li Be able to balance a variety of different projects and tasks
                %li Be highly motivated and be able to take control of your own time and responsibilities
                %li Want to work with a startup and want to learn new skills

            %p It will also help if you have:
            %ul
                %li Worked as a community manager before
                %li Some experience in marketing or growth hacking
                %li Worked in an agile team

            =jobs_apply_blurb
        .span3 
            =render "jobs/sidebar"

app/views/jobs/principles.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Working at Meducation
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Jobs", jobs_path
                %span.divider /
            %li.active Working at Meducation

.container
    .row-fluid
        .span9
            .headline
                %h3 Our Principles
            .row-fluid
                .span8
                    %p At Meducation, we believe that the key to our success is building a team who trust and respect each other, who enjoy each others' company and who love working together.  We know that each person is an individual and works in their own way, and its important to us that we respect and encourage that. We want our team to have the freedom to manage their own time and tasks, while getting stuck in to help each other build an amazing platform that has the potential to change the world.
                    %p 
                        Taking advice from successful companies like 
                        =succeed(',') do
                            =link_to "Github", "http://zachholman.com/posts/how-github-works/", title: "How Github Works"
                        =succeed(',') do
                            =link_to "Valve", "http://www.valvesoftware.com/company/Valve_Handbook_LowRes.pdf", title: "The Valve Handbook"
                        =succeed(', and ') do
                            =link_to "37signals", "http://www.inc.com/magazine/20110401/jason-fried-why-i-run-a-flat-company.html", title: "Why I Run a Flat Company"
                        =succeed(',') do
                            =link_to "Medium", "http://firstround.com/article/How-Medium-is-building-a-new-kind-of-company-with-no-managers#", title: "How Medium is building a new kind of company with no managers"
                        here are some of our principles with regards to work.
                            
                .span4= image_tag('office.jpg')
            %blockquote.hero.margin-top-20
                %p If we start treating people like people, and not workhorses, we can build work lives that make us better off and our world a little bit better.
                %small Dan Pink - The Surprising Truth About What Motivates Us.

            .headline
                %h3 Self-Direction
            .row-fluid
                .span4
                    .flex-video.widescreen
                        <iframe src="//www.youtube.com/embed/TABgBBuxP9k?rel=0" frameborder="0" allowfullscreen></iframe>
                .span8
                    %p 
                        We want our team to have the freedom to work where they want, when they want, but we also think that working together allows for serendipitous creativity, a team bond, and shared highs and lows. We try to balance these paradoxical traits by being 
                        =link_to "very relaxed about office hours", "http://zachholman.com/posts/how-github-works-hours/"
                        and location, but by making sure we have some time each week where our team work together to work in one place.
                    %p We also believe that having control of your own tasks and your own role is the most satisfying and inspiring way to work. We are therefore building a team of highly-motivated free-thinkers who trust each other to deliver and support each other.

            .headline
                %h3 The Right Motivation
            .row-fluid
                .span8
                    %p Smart people like interesting challenges. We believe that learning new concepts, theories, and technologies, and going on to master them is the most satisfying way to work. Meducation is full of hard problems to solve, both technologically and socially, but we are going to solve them.
                    %p We also agree with Dan Pink (see video) that motivating by money doesn't make sense. We want our team to be paid fairly, without the pressure of performance-related bonuses. Work because you're passionate, not because you have to.
                .span4
                    .flex-video.widescreen
                        <iframe src="//www.youtube.com/embed/u6XAPnuFjJc?rel=0" frameborder="0" allowfullscreen></iframe>

            .headline
                %h3 Helping The Bigger Community

            .span3.pull-right
                %blockquote
                    %p If i have seen further, it is by standing on the shoulders of giants.
                    %small Sir Isaac Newton
            %p Meducation is all about community and this is represented in the way we work. Our platform is built on open-source software, and much of it will be contributed back through open source. We encourage our team to write articles and speak at conferences about the things we learn, so that others can benefit from both our successes and our failures.
            %p We also encourage our team to have their own ideas and projects outside of Meducation and we support each other in them. Life is better when it's varied.
            
        -#
            .row-fluid.servive-block
                .span4
                    %h4 Work when's right for you
                    %p
                        %i.icon-time
                    %p We don't have office hours because we know that different people work best at different times. Rise with the sun, or rise with the sunset? We respect your choice.
                .span4
                    %h4 Work where's best for you
                    %p
                        %i.icon-home
                    %p Office, home, coffee-shop? Your choice. We hope you'll want to hang out with us in the office reguarly, but we don't work as well if we're in the same place each day, and so we understand that freedom.
                .span4
                    %h4 Be paid well and fairly
                    %p
                        %i.icon-gbp
                        %p We should all feel that we are paid what we deserve. We want to pay fairly and don't believe in performance-related pay, which just increases pressure &amp; stress. 
            .row-fluid.servive-block
                .span4
                    %h4 Be challenged and learn
                    %p
                        %i.icon-puzzle-piece
                .span4
                    %h4 Create your own projects.
                    %p
                        %i.icon-sitemap
                .span4
                    %h4 Contribute to open source
                    %p
                        %i.icon-cloud
                    %p We're really passionate about open source and intend to release 90% of our code under open source licences. If you're a developer, you'll be working with us to build libraries that power the internet, not just Meducation!

        .span3 
            =render "jobs/sidebar"

app/views/jobs/ror_developer.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Job Opportunities
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Jobs", jobs_path
                %span.divider /
            %li.active Ruby on Rails Developer

.container
    .row-fluid
        .span9
            .headline
                %h3 We are Hiring a Ruby on Rails Developer
            %p We are building an innovative social education platform that will be used by milions of medics. It is technologically centred around Rails and Angular. 
            %p Meducation is currently a single large Ruby on Rails application that we are breaking into an API centred around a service orientated architecture, which will power an single page javascript application. We are looking for an experienced Rails developer to help with this process and build our application as it develops. We believe in using the right technology for the right circumstances and so the right person for this role will enjoy working with a variety of languages and frameworks.
            =jobs_startup_blurb

            %h3 What specific skills are we looking for?
            %p If you're right for this role, you will: 
            %ul
                %li Have 4+ years of development experience (either professionally or in demonstratable personal projects)
                %li Have 2+ years working with Ruby on Rails and the associated stack (e.g. SQL, JS, AWS)
                %li Have excellent development skills 
                %li Enjoy learning new languages and be comfortable switching between technologies
                %li Be able to balance a variety of different projects and tasks
                %li Be highly motivated and be able to take control of your own time and responsibilities
                %li Want to work with a startup and want to learn new skills

            %p It will also help if you have:
            %ul
                %li A computer science (or related) degree
                %li A passion for open source
                %li Worked in an agile team

            =jobs_apply_blurb
        .span3 
            =render "jobs/sidebar"

app/views/jobs/ruby_on_rails_developer.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Job Opportunities
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Jobs", jobs_path
                %span.divider /
            %li.active Ruby on Rails Developer

.container
    .row-fluid
        .span9
            .headline
                %h3 We are Hiring a Ruby on Rails Developer
            %p We are building an innovative social education platform that will be used by millions of medics.
            %p Meducation is currently a large Ruby on Rails application, which we are breaking into a service-orientated architecture. Rails will remain at the centre of Meducation, but will supported by services in a variety of other technologies. We are looking for an experienced Ruby on Rails developer to help break this single application into multiple services, and to continue to build new software in Rails. Proven Rails skills are important for this role as we need someone who can hit the ground running, but we are also looking for someone who is comfortable learning other technologies so they can get muck in across the stack.
            =jobs_startup_blurb

            %h3 What specific skills are we looking for?
            %p If you're right for this role, you will: 
            %ul
                %li Have 3+ years working with Ruby on Rails (either professionally or in demonstrable personal projects)
                %li Have excellent Ruby on Rails knowledge and skills 
                %li Be able to balance a variety of different projects and tasks
                %li Be highly motivated and be able to take control of your own time and responsibilities
                %li Want to work with a startup and want to learn new skills

            %p It will also help if you have:
            %ul
                %li A computer science (or related) degree
                %li A passion for open source
                %li Worked in an agile team

            =jobs_apply_blurb
        .span3 
            =render "jobs/sidebar"

app/views/jobs/software_developer.html.haml
.row-fluid.breadcrumbs.margin-bottom-20
    .container
        %h1.pull-left Job Opportunities
        %ul.pull-right.breadcrumb
            %li
                =link_to "Home", root_path
                %span.divider /
            %li
                =link_to "Jobs", jobs_path
                %span.divider /
            %li.active Software Developer

.container
    .row-fluid
        .span9
            .headline
                %h3 We are Hiring an Experienced Software Developer
            %p We are building an innovative social education platform that will be used by milions of medics. 
            %p Meducation is being developed as a service-orientated architecture because we believe it is important to use the the right technology for the right situation. We are looking for an experienced software developer who is comfortable learning technologies and languages to help build our platform. If you're the right person for this role you will care about good software development principles, understand which technologies are needed for which situations, and be able to quickly implement high quality code.
            =jobs_startup_blurb

            %h3 What specific skills are we looking for?
            %p If you're right for this role, you will: 
            %ul
                %li Have 4+ years of development experience (either professionally or in demonstratable personal projects)
                %li Have excellent development skills 
                %li Understand and care about software principles (e.g. SOLID)
                %li Enjoy learning new languages and be comfortable switching between technologies
                %li Be able to balance a variety of different projects and tasks
                %li Be highly motivated and be able to take control of your own time and responsibilities
                %li Want to work with a startup and want to learn new skills

            %p It will also help if you have:
            %ul
                %li A computer science (or related) degree
                %li A passion for open source
                %li Worked in an agile team

            =jobs_apply_blurb
        .span3 
            =render "jobs/sidebar"